#
# GitLab CI/CD Pipeline for deploying DreamHouse App using Salesforce DX
#
#
# Run these commands before executing any build jobs,
# such as to install dependencies and set environment variables
#
before_script:
    # Decrypt server key
    - openssl enc -aes-256-cbc -md sha256 -salt -d -in assets/server.key.enc -out assets/server.key -k $SERVER_KEY_PASSWORD 

    - sfdx --version
    - sfdx plugins --core
#
# Define the stages of our pipeline
#
stages:
    - validation
    - integration-testing
    - app-deploy
#
# Stage 1 -- Create a scratch org for code testing
#
validation:
    stage: validation
    when: manual
    script:
        # Authenticate to the Dev Hub using the server key

        #- sfdx force:auth:jwt:grant --setdefaultdevhubusername --setalias DevHub --clientid $SF_CONSUMER_KEY --jwtkeyfile assets/server.key --username $SF_USERNAME
        - sfdx force:auth:jwt:grant --clientid 3MVG9Oe7T3Ol0ea6If.Q8PidWvzWGH8jAc2ibBnIhV_C0ohx9Nj0YZlA6mrEfaEZfOC5ySuWMTHMv332leiFF --jwtkeyfile assets/server.key --username jhoskins@insightpartners.com.fullcopy --instanceurl https://test.salesforce.com
        #- sfdx force:org:create --setdefaultusername --definitionfile config/project-scratch-def.json --targetdevhubusername $SF_USERNAME --wait 10 --durationdays 7
        #- sfdx force:org:display
        # Push source to scratch org (this is with source code, all files, etc)
        - sfdx force:config:set restDeploy=true
        #- sfdx force:source:deploy -x manifest/package.xml --checkonly --targetusername jhoskins@insightpartners.com.fullcopy --runtests RunLocalTests
        - sfdx force:source:deploy --sourcepath force-app -l RunLocalTests -c --targetusername jhoskins@insightpartners.com.fullcopy

        # Unit Testing
        # - sfdx force:apex:test:run --wait 10 --resultformat human --codecoverage --testlevel RunLocalTests
        # Delete Scratch Org
        #- sfdx force:org:delete --noprompt
#
# Stage 2 -- Create a scratch org, create a package version, and push into org for testing
#

#
# Stage 3 -- Promote the package to downstream environment for UAT for example
#
